openapi: 3.0.3
info:
  title: Swagger Recommendation System - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
    
    Some useful links:
    - [The Recommendation System repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Recommendation System](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

  #termsOfService: http://swagger.io/terms/
  contact:
    email: jesuspaucruz@gmail.com
  #license:
  #  name: Apache 2.0
  #  url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
#externalDocs:
#  description: Find out more about Swagger
#  url: http://swagger.io
#servers:
#  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: user
    description: Operations about user
paths:
  /user/{userId}/actions:
    post:
      tags:
        - user
      summary: Register specific actions of the web user
      operationId: registerAction
      parameters:
        - name: userId
          in: path
          description: user ID that need to register action
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum: [view, add-to-cart, purchase]
                productId:
                  type: string
                timestamp:
                  type: string
      responses:
        '200':
          description: Successful operation