global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: zookeeper
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["zookeeper:9200"]

  - job_name: brokers
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["broker1:9200", "broker2:9201", "broker3:9202"]

  - job_name: schema-registry
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["schema-registry:9203"]

  - job_name: connect
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["connect:9204"]

  - job_name: recommendation-system
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ["recommendation-system-ms:8080"]